name: First Workflow
on: [push, workflow_dispatch]
branch: main
jobs: 
    first-job: 
      runs-on: windows-latest
      steps:
        - name: Print greeting 
          run: echo "Hello World"
        - name: echo "Done - bye"
          run: echo "Hi"

    second-job: 
      needs: first-job
      runs-on: windows-latest
      steps:
        - name: Print greeting 
          run: echo "Hello World"
        - name: echo "Done - bye"
          run: echo "Hi"
